- name: "Install nginx"
  when: web.server == 'nginx'
  apt:
    name: "nginx"

- name: "Check for nginx config file"
  stat:
    path: "{{ snitch.destination }}/data/config/http/vhost.conf"
  register: http_config

- name: "Check for enabled vhost"
  stat:
    path: /etc/nginx/sites-enabled/snitch
  register: enabled_host

- name: "Creating config"
  when: http_config.stat.exists == False
  template:
    src: ubuntu/nginx/vhost.conf.j2
    dest: "{{ snitch.destination }}/data/config/http/vhost.conf"

- name: "Enabling vhost"
  when: enabled_host.stat.exists == False
  file:
    src: "{{ snitch.destination }}/data/config/http/vhost.conf"
    dest: "/etc/nginx/sites-enabled/snitch"
    state: link

- name: "Restarting nginx"
  service:
    name: nginx
    state: restarted